// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXafvCk4VVVF-IFBbZCOtjoUi-rIri-bk',
    appId: '1:627905383308:web:c16e641cc173ff26d224a9',
    messagingSenderId: '627905383308',
    projectId: 'rationshop-aeea7',
    authDomain: 'rationshop-aeea7.firebaseapp.com',
    storageBucket: 'rationshop-aeea7.appspot.com',
    measurementId: 'G-8W023KGJ6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPSEWJSRPMyupjcpJbhcujFojH5C8MNA',
    appId: '1:627905383308:android:35dfbdfa16f0ee63d224a9',
    messagingSenderId: '627905383308',
    projectId: 'rationshop-aeea7',
    storageBucket: 'rationshop-aeea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcO9SFQUqGEnnst3Wxn2g50QRctKPdHGk',
    appId: '1:627905383308:ios:502f87521ade3790d224a9',
    messagingSenderId: '627905383308',
    projectId: 'rationshop-aeea7',
    storageBucket: 'rationshop-aeea7.appspot.com',
    iosClientId: '627905383308-1r9h3d32jmdvkegnrc5fe8gdbmb8mqch.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcO9SFQUqGEnnst3Wxn2g50QRctKPdHGk',
    appId: '1:627905383308:ios:502f87521ade3790d224a9',
    messagingSenderId: '627905383308',
    projectId: 'rationshop-aeea7',
    storageBucket: 'rationshop-aeea7.appspot.com',
    iosClientId: '627905383308-1r9h3d32jmdvkegnrc5fe8gdbmb8mqch.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveringApp',
  );
}
